server:
  port: 8080

spring:
  profiles:
    active: dev

  main:
    allow-circular-references: true

  datasource:
    druid:
      driver-class-name: ${enjoy.datasource.driver-class-name}
      url: jdbc:mysql://${enjoy.datasource.host}:${enjoy.datasource.port}/${enjoy.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: ${enjoy.datasource.username}
      password: ${enjoy.datasource.password}
      connection-timeout: ${enjoy.datasource.timeout}
      validation-timeout: ${enjoy.datasource.timeout}
      max-lifetime: ${enjoy.datasource.lifetime}
      maximum-pool-size: ${enjoy.datasource.pool.max}
      minimum-idle: ${enjoy.datasource.pool.idle}

  data:
    redis:
      host: ${enjoy.redis.host}
      port: ${enjoy.redis.port}
      password: ${enjoy.redis.password}
      database: ${enjoy.redis.database}

mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.helltractor.enjoy.entity
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true

logging:
  level:
    com.helltractor.enjoy:
      mapper: debug
      service: info
      controller: info

enjoy:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: itcast
    # 设置jwt过期时间
    admin-ttl: 7200000
    # 设置前端传递过来的令牌名称
    admin-token-name: token
    user-secret-key: itheima
    user-ttl: 7200000
    user-token-name: authentication

  alioss:
    endpoint: ${enjoy.alioss.endpoint}
    access-key-id: ${enjoy.alioss.access-key-id}
    access-key-secret: ${enjoy.alioss.access-key-secret}
    bucket-name: ${enjoy.alioss.bucket-name}

  wechat:
    appid: ${enjoy.wechat.appid}
    secret: ${enjoy.wechat.secret}

  shop:
    address: 浙江省钱塘区杭州市311222

  baidu:
    ak: your-ak
